version: '3.8'

services:
  api:
    image: api:v1
    container_name: 'api'
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - 3000:3000

  postgres-db:
    image: postgres
    container_name: 'postgres-db'
    env_file:
      - ../.env
    ports:
      - "5432:5432"
